### ISSUE TITLE
Translating FishFeed to Dutch and German

### ISSUE THREAD

**Issue by qlpham231** [vr4vet/Blue-Sector#176]
Translations needed in Dutch and German:
1. Welcome to the food station! Your task is to feed the fish so that it gets the right amount of food. Enter the house to proceed. 
2. Here you are going to choose the difficulty level of the game:  - Select basic level if you have never played before.  - Choose advanced level if you know how to play and are ready for a challenge. 
3. Observe the fish:  - They swim up to eat when they are hungry.  - They swim down when they are full.  - The feed will fall to the bottom when the fish are full.  Use the control panel on the table to adjust the camera and the amount of feed given to the fish. There are three fish cages, and you have to keep an eye on all of them! 
4. Stairs
5. Difficulty level
6. Control room
7. Current level
8. Basic
9. Advanced
10. Press A to start the game 
11. Rotate the camera with the joystick
12. Move camera forward or backward
13. Move camera up or down
14. Adjust the amount of feed given to the fish
15. Select which cage that appears on the screen
16. Grab the screen to experience the cage up close
17. Observe and make sure that they are not over- or under-fed.
18. The fish is hungry. Increase the amount of feed.
19. The fish is full. Slow down the feeding to not waste feed.

Where the text appear in the game:
1. On the welcome sign
2. Info board when the player is going to pick level
3. Signboard where they start playing
4. Arrow sign pointing to stairs
5. Arrow sign
6. Arrow sign
7. Hovering text over buttons
8. Hovering text over the button
9. Hovering text over the button
10. Tooltip
11-19. Tutorial tooltip

**Comment by ottedam** [comment]
The following is Dutch:

1. Welkom bij de voederruimte! Jouw taak is om de vissen te voederen tot ze de juiste hoeveelheid voedsel hebben. Ga het huis binnen om verder te gaan.
2. Hier kies je de moeilijkheidsgraad van het spel:
- Selecteer 'basis level' als je dit nog nooit hebt gespeeld.
- Selecteer 'gevorderde level' als je al weet hoe het spel werkt en je klaar bent voor een uitdaging.
3. Observeer de vissen:
- Ze zwemmen naar boven om te eten als ze honger hebben
- Ze zwemmen naar beneden als ze vol zijn
- Het voer zal naar beneden vallen als de vissen vol zijn. Gebruik het controle paneel op de tafel om de camera en de hoeveelheid voer voor de vissen aan te passen. Er zijn drie vissenkooien, en je moet ze allemaal in de gaten houden!
4. Trap (singular) trappen (plural)
5. Moeilijkheidsgraad
6. Controle kamer
7. Huidige level
8. Basis
9. Gevorderd
10. Klik op A om het spel te starten.
11. Draai de camera met de joystick.
12. Beweeg de camera naar voren of naar achteren.
13. Beweeg de camera naar boven of naar beneden.
14. Verander de hoeveelheid voer die aan de vissen wordt gegeven.
15. Selecteer welke kooi op het scherm wordt weer gegeven.
16. Pak het scherm om de kooi van dichtbij te ervaren.
17. Observeer en zorg dat ze niet over- of ondervoed zijn.
18. De vissen hebben honger. Verhoog de hoeveelheid voer.
19. De vissen zijn vol. Verminder het voederen om geen voer te verspillen.
