### ISSUE TITLE
Stairs are slow to navigate

### ISSUE THREAD

**Issue by SnorreForbregd** [vr4vet/Blue-Sector#191]
Based on demo during Trøndersk Matfestival (Trøndelag Food Festival), people try to move many steps at once, and will spend more time trying to get a higher step rather than moving smaller steps.

The reason this takes so long is that each step only has a slim area, and the higher up the step, the more difficult it is to accurately aim in the middle.

A fix would be to have the stair have the hitbox of a slope, meaning every part of the stair would be teleportable.

**Comment by fominykh** [comment]
Alternative 2: add a teleport upstairs (one teleport to move upstairs in one click)
Alternative 3: move the control room to the first floor.

**Comment by ingolvjr** [comment]
Teleporting would be the easiest, I just need to find out how to determine whether the player is on the 1st or 2nd floor
