### ISSUE TITLE
Speedboat to Fish Welfare can be teleported over, leading to falling into water

### ISSUE THREAD

**Issue by SnorreForbregd** [vr4vet/Blue-Sector#192]
It is possible to miss the speedboat leading to fish welfare, which leads to teleporting to the edge of the boat and falling into the water.

Temporary fix is in place that teleports player back to the boat, but should be fixed.

**Comment by ingolvjr** [comment]
The issue stems from the outer edge of the boat being valid teleport areas but not standable so the player slides off.

The user also doesn't trigger the transition AoE when missing like this because the AoE is too small

**Comment by ingolvjr** [comment]
I will fix the issue with expanding the AoE and setting up some boundaries, but think it would be smart to hold off on this since @eamathie is currently also working on the boat

**Comment by ingolvjr** [comment]
Closed by pr #197
