### ISSUE TITLE
Unused area of Fish Feed building should be accessible

### ISSUE THREAD

**Issue by SnorreForbregd** [vr4vet/Blue-Sector#195]
Currently, it is possible to physically walk through the wall to access this area.

Based on demo during Trøndersk Matfestival (Trøndelag Food Festival), many people tried to enter the door on the 1st floor, which leads to this unused area.

All doors should be dynamic/allow the user to pass through (in-app). The unused area should also be decorated, but does not need to serve any function at the moment.

**Comment by ingolvjr** [comment]
Closed by https://github.com/vr4vet/Blue-Sector/pull/351/commits/ed7ab09d86e0ff1f4ca220c1800f43b60a164e27
