### ISSUE TITLE
Joystick, levers, and sliders can be put into player's pockets.

### ISSUE THREAD

**Issue by SnorreForbregd** [vr4vet/Blue-Sector#196]
The joystick, levers, and sliders on the Fish Feeding control panel can be pulled into the player's pockets. Combined with issue #182, this can lead to them getting stuck in the belt, making it impossible to play.

**Comment by ingolvjr** [comment]
There is a property on the grabbable component that can disable whether it can be put into snap zones(I think the holsters are the only ones in the scene) which is enabled by default.
