### ISSUE TITLE
Update Fish System Logic

### ISSUE THREAD

**Issue by qlpham231** [vr4vet/Blue-Sector#35]
## Definition of Done
- [x] Hunger is moved from fish to school of fish as a whole
- [x] Fish death is moved from fish to school of fish as a whole
  - [x] School of fish has a total fish count
  - [x] Fish count is reduced over time if school of fish is hungry
- [x] School of fish moves up in cage if hungry + feed in water
- [x] School of fish moves together
  - [ ] Some fish move before/after others
  - [ ] Some fish move randomly
- [x] Food particles are removed if they get "eaten"

**Comment by eamathie** [comment]
The two tasks of fish moving before/after others and randomly are not implemented explicitly at the moment, because the movement already looks quite random. They can of course be implemented if necessary, and I think we should discuss this. Will move on to other issues for the time being.
