### ISSUE TITLE
Replace conveyor belts

### ISSUE THREAD

**Issue by krisgjol** [vr4vet/Blue-Sector#354]
Replace the current conveyor belts with the better ones from a different project.
Technical coordinator remarked that the ones currently used are not acceptible, and there should be a better conveyor prefab in an eariler project. The belt should should be black, and the joints and such should be way better

**Comment by mefriis** [comment]
Did it become clear which earlier project? From GitLab? Fiskeprosjekt VR, or from FishFarm, or from another non-aquculture related project? And, why was the conveyor not acceptable? Because of the joints?
