### ISSUE TITLE
Fish Game State

### ISSUE THREAD

**Issue by qlpham231** [vr4vet/Blue-Sector#38]
## Description
After the game is done the fish should swim around and not gain hunger.
The user should not be penalized before the game has started.

## Definition of Done
- [x] Fish idle state
  - [x] Fish do not get hungry
  - [x] Fish do not die
- [x] Fish active state
  - [x] Fish get hungry over time
  - [x] Fish die if hungry for too long 
- [x] Fish enter idle state on scene load
- [x] Fish enter idle state after game end
- [x] Fish enter active state on game start

**Comment by fominykh** [comment]
I think this applies alto to Before the game starts.
Ideally, we would have an NPC in the control room who is there to control the feeding (story-wise). When the user starts the game, the user takes control from the NPC, from the story/scenario point of view.
