### ISSUE TITLE
Implement LOD on fish to increase performance

### ISSUE THREAD

**Issue by qlpham231** [vr4vet/Blue-Sector#39]
Reduce polygon count for fish based on distance.

## Definition of Done:
- [ ] Model 3 distinct fish models by simplifying the geometry of the existing fish model.
  - [x] Experiment with a sprite when the distance is very large. (This might only look good with a high number of fish).
- [ ] Implement LOD by switching between these models based on distance.

**Comment by fominykh** [comment]
Which objects did you want to apply LOD to? Fish?

**Comment by eamathie** [comment]
Yes

**Comment by eamathie** [comment]
I updated the description now to make it more specific.
