### ISSUE TITLE
Implement and Visualise gameplay hints

### ISSUE THREAD

**Issue by qlpham231** [vr4vet/Blue-Sector#40]
## Description
Implement gameplay hints in the form of pop-ups informing the player on the next logcial action to take if they are failing over time, and the player is in _Arcade Mode_.

## Definition of Done
- [ ] Hints are written
- [ ] Hints are displayed if player is idle too long at the start of scenario
  - [ ] Show hint: feeding control
- [ ] Hints are displayed when player is failing
  - [ ] Fish are hungry over time and player is not feeding
    - [ ] Show hint: Fish are hungry, use control to feed
  - [ ] Fish are full and player does not stop feeding over time
    - [ ] Show hint: Fish are full, food is being wasted
  - [ ] Player is not changing camera to different cage and fish are hungry over time / begin dying
    - [ ] Display warning about fish being hungry / dying in different cage
  - [ ] Player is not moving camera position
    - [ ] Show hint: use joystick to move camera
  - [ ] Player does not move feeding control out of one position, or only uses max and of or similar
    - [ ] Show hint: Use the slider to adjust amount, [ food is being wasted | fish aren't recieving enough food ]
- [ ] Hints are displayed next to relevant control surfaces (if applicable)
- [ ] Control tips are shown once (e.g. "push button to change camera")
- [ ] Warnings  are shown through whole tutorial level (e.g. fish dying in other cage)

**Comment by fominykh** [comment]
FYI, in the next release of the code functions, we will have a tooltip prefab. Tooltip is a hint UI element attached to specific objects (e.g., tools). Check here: https://github.com/orgs/vr4vet/projects/7
Other similar UI elements will be coming later. If you want make some that are potentially applicable to any profession workspace, I can give you the basic design guidelines for them.

**Comment by trympet** [comment]
@fominykh, nice. I already made a crude implementation of this, so we can swap it out once it's released.
