### ISSUE TITLE
Improve filestructure in fish factory

### ISSUE THREAD

**Issue by jonp-h** [vr4vet/Blue-Sector#400]
This includes changing:
- [x] Script folder structure
- [x] Prefab folder structure
- [x] Materials
- [x] Sounds
- [x] Common files
- [x] All prefabs should be moved into a "Resources/Prefabs" folder

**Comment by MarkusJohansen** [comment]
#401 Moves all prefabs into Resources Folder

**Comment by mefriis** [comment]
Reorganized materials folder and prefabs folder, and moved assets from the PreviousFishFactory (Old project) folder into their respective folder.

**Comment by jonp-h** [comment]
> Reorganized materials folder and prefabs folder, and moved assets from the PreviousFishFactory (Old project) folder into their respective folder. Removed unused materials and prefabs. Gone through all the scenes to look for missing materials or prefabs, could not find any.

Wonderful job!
