### ISSUE TITLE
Write more unit tests for Fish Factory

### ISSUE THREAD

**Issue by MarkusJohansen** [vr4vet/Blue-Sector#463]
We need better test coverage for fish factory. Here is some suggestions for important scripts to start testing, with varying complexion: 
- [x] GuttingFishSorting.cs
- [x] CutFishGill.cs
- [x] CutFishBody.cs.
- [x] FactoryFishState.cs
- [x] Despawner.cs
- [x] CutFish.cs
- [x] FishSortingTrigger.cs
- [x] DiscardKnife.cs
- [x] StunFish.cs

**Comment by ingolvjr** [comment]
Partially solved by #487

**Comment by ingolvjr** [comment]
Partially solved by #513

**Comment by ingolvjr** [comment]
FactoryFishState.cs should be tested before CutFishGill.cs, CutFishBody.cs and CutFish.cs
