### ISSUE TITLE
Cleanup code

### ISSUE THREAD

**Issue by Herman1412** [vr4vet/Blue-Sector#467]
We need to ensure consistent code conventions throughout the entirety of the project. The following conventions we will commit to are:

- [x] Csharpier code formatting
- [x] prefixes for private variables `_` and constants `k_` 
- [x] Use `private [SerializeField]` over public variables.
- [x] Fix comments in GutFish.cs
- [x] Optimize code

**Comment by MarkusJohansen** [comment]
closed by #471
