### ISSUE TITLE
Fish inventory issues

### ISSUE THREAD

**Issue by Herman1412** [vr4vet/Blue-Sector#567]
The fish should only contain one grabbable on the parent object.
The grabbable script should instead make use of grab points on each of the bones.

- [ ] Factory fish
- [ ] Welfare fish

**Comment by ingolvjr** [comment]
The fish pretty much only works as is, but the logic with the inventory and transfer between scenes needs to be reworked:

1. Use ResetParent from Grabbable.cs to restore the fish to one GameObject
2. get the root object of the fish
3. Clone the whole fish
4. load new scene
5. insert fish clone into the correct snap zone

Similar logic may be used to fix inventory issue, there is an "OriginalParent" value in Grabbable.cs but it is protected

**Comment by ingolvjr** [comment]
I am finishing my apprenticeship at IMTEL and will not work on this anymore

**Comment by Herman1412** [comment]
Fish can be placed in the "pop up inventory "and taken out of it. However closing and reopening it will cause the fish to shrink a little.
