### ISSUE TITLE
Remodel house

### ISSUE THREAD

**Issue by qlpham231** [vr4vet/Blue-Sector#63]

**Comment by eamathie** [comment]
@fominykh , what are the most pressing issues regarding the house in the demo? I remember that you mentioned that it was too small, and that there are many rooms in the real building (storage etc), and that you were gonna send some images. Should the house ideally be a copy of the one we visited, or just generally the same layout? What rooms should the player have access to (all? are some more important than others?).

**Comment by fominykh** [comment]
A general layout would be nice. Everything can be empty for now, except for the control room.
